<a href="https://colab.research.google.com/github/engSalah-dot/Machine-Learning-from-scratch-to-advanced/blob/main/Bank%20Customer%20Churn%20Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [188]:
from sklearn import svm
from sklearn.metrics import*
from sklearn.feature_selection import chi2,SelectPercentile,SelectKBest,SelectFromModel
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

In [189]:
data=pd.read_csv('/content/Churn_Modelling.csv')
data=pd.DataFrame(data)
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [190]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [191]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [192]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [193]:
data.shape

(10000, 14)

In [194]:
null_sum=data.isnull().sum()
null_sum

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [195]:
data=data.drop(['RowNumber',	'CustomerId',	'Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [196]:
data=pd.get_dummies(data,drop_first=True)

In [197]:
data['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [198]:

X=data.drop('Exited',axis=1)

Y=data['Exited']

In [199]:
from imblearn.over_sampling import SMOTE
x_res,y_res=SMOTE().fit_resample(X,Y)
y_res.value_counts()

Exited
1    7963
0    7963
Name: count, dtype: int64

In [200]:
X_train,X_test,Y_train,Y_test=train_test_split(x_res,y_res,test_size=0.2,random_state=42)

In [201]:
st=StandardScaler()
X_train=st.fit_transform(X_train)
X_test=st.transform(X_test)

In [202]:
LR=LogisticRegression()
LR.fit(X_train,Y_train)
y_pred1=LR.predict(X_test)
print( f"precision_score : { precision_score(Y_test,y_pred1)}")
print(f"accuracy_score   :{accuracy_score(Y_test,y_pred1)}")
print(f"recall_score     :{recall_score(Y_test,y_pred1)}")
print(f"f1_score         :{f1_score(Y_test,y_pred1)}")
print(f"roc_auc_score    :{roc_auc_score(Y_test,y_pred1)}")
print(f"confusion_matrix :\n {confusion_matrix(Y_test,y_pred1)}")
print(f"classification_report :\n {classification_report(Y_test,y_pred1)}")

precision_score : 0.7698717948717949
accuracy_score   :0.7768361581920904
recall_score     :0.7733419188667096
f1_score         :0.7716029553485384
roc_auc_score    :0.7767505675166371
confusion_matrix :
 [[1274  359]
 [ 352 1201]]
classification_report :
               precision    recall  f1-score   support

           0       0.78      0.78      0.78      1633
           1       0.77      0.77      0.77      1553

    accuracy                           0.78      3186
   macro avg       0.78      0.78      0.78      3186
weighted avg       0.78      0.78      0.78      3186

In [203]:
svm=svm.SVC()
svm.fit(X_train,Y_train)
y_pred2=svm.predict(X_test)
print( f"precision_score : { precision_score(Y_test,y_pred2)}")
print(f"accuracy_score   :{accuracy_score(Y_test,y_pred2)}")
print(f"recall_score     :{recall_score(Y_test,y_pred2)}")
print(f"f1_score         :{f1_score(Y_test,y_pred2)}")
print(f"roc_auc_score    :{roc_auc_score(Y_test,y_pred2)}")
print(f"confusion_matrix :\n {confusion_matrix(Y_test,y_pred2)}")
print(f"classification_report :\n {classification_report(Y_test,y_pred2)}")

precision_score : 0.8419672131147541
accuracy_score   :0.839924670433145
recall_score     :0.8267868641339343
f1_score         :0.834307992202729
roc_auc_score    :0.8396028625629869
confusion_matrix :
 [[1392  241]
 [ 269 1284]]
classification_report :
               precision    recall  f1-score   support

           0       0.84      0.85      0.85      1633
           1       0.84      0.83      0.83      1553

    accuracy                           0.84      3186
   macro avg       0.84      0.84      0.84      3186
weighted avg       0.84      0.84      0.84      3186

In [204]:
knn=KNeighborsClassifier()
knn.fit(X_train,Y_train)
y_pred3=knn.predict(X_test)
print( f"precision_score : { precision_score(Y_test,y_pred3)}")
print(f"accuracy_score   :{accuracy_score(Y_test,y_pred3)}")
print(f"recall_score     :{recall_score(Y_test,y_pred3)}")
print(f"f1_score         :{f1_score(Y_test,y_pred3)}")
print(f"roc_auc_score    :{roc_auc_score(Y_test,y_pred3)}")
print(f"confusion_matrix :\n {confusion_matrix(Y_test,y_pred3)}")
print(f"classification_report :\n {classification_report(Y_test,y_pred3)}")

precision_score : 0.816793893129771
accuracy_score   :0.825172630257376
recall_score     :0.8267868641339343
f1_score         :0.82176
roc_auc_score    :0.8252121705850322
confusion_matrix :
 [[1345  288]
 [ 269 1284]]
classification_report :
               precision    recall  f1-score   support

           0       0.83      0.82      0.83      1633
           1       0.82      0.83      0.82      1553

    accuracy                           0.83      3186
   macro avg       0.83      0.83      0.83      3186
weighted avg       0.83      0.83      0.83      3186

In [205]:
Dt=DecisionTreeClassifier()
Dt.fit(X_train,Y_train)
y_pred4=Dt.predict(X_test)
print( f"precision_score : { precision_score(Y_test,y_pred4)}")
print(f"accuracy_score   :{accuracy_score(Y_test,y_pred4)}")
print(f"recall_score     :{recall_score(Y_test,y_pred4)}")
print(f"f1_score         :{f1_score(Y_test,y_pred4)}")
print(f"roc_auc_score    :{roc_auc_score(Y_test,y_pred4)}")
print(f"confusion_matrix :\n {confusion_matrix(Y_test,y_pred4)}")
print(f"classification_report :\n {classification_report(Y_test,y_pred4)}")

precision_score : 0.8020176544766708
accuracy_score   :0.8132454488386692
recall_score     :0.8190598840952994
f1_score         :0.8104491876393756
roc_auc_score    :0.8133878722374844
confusion_matrix :
 [[1319  314]
 [ 281 1272]]
classification_report :
               precision    recall  f1-score   support

           0       0.82      0.81      0.82      1633
           1       0.80      0.82      0.81      1553

    accuracy                           0.81      3186
   macro avg       0.81      0.81      0.81      3186
weighted avg       0.81      0.81      0.81      3186

In [206]:
Rf=RandomForestClassifier()
Rf.fit(X_train,Y_train)
y_pred5=Rf.predict(X_test)
print( f"precision_score : { precision_score(Y_test,y_pred5)}")
print(f"accuracy_score   :{accuracy_score(Y_test,y_pred5)}")
print(f"recall_score     :{recall_score(Y_test,y_pred5)}")
print(f"f1_score         :{f1_score(Y_test,y_pred5)}")
print(f"roc_auc_score    :{roc_auc_score(Y_test,y_pred5)}")
print(f"confusion_matrix :\n {confusion_matrix(Y_test,y_pred5)}")
print(f"classification_report :\n {classification_report(Y_test,y_pred5)}")

precision_score : 0.8676184295911745
accuracy_score   :0.8681732580037664
recall_score     :0.8609143593045718
f1_score         :0.8642533936651584
roc_auc_score    :0.8679954527692485
confusion_matrix :
 [[1429  204]
 [ 216 1337]]
classification_report :
               precision    recall  f1-score   support

           0       0.87      0.88      0.87      1633
           1       0.87      0.86      0.86      1553

    accuracy                           0.87      3186
   macro avg       0.87      0.87      0.87      3186
weighted avg       0.87      0.87      0.87      3186

In [212]:
GB=GradientBoostingClassifier()
GB.fit(X_train,Y_train)
y_pred6=GB.predict(X_test)
print( f"precision_score  :{precision_score(Y_test,y_pred6)}")
print(f"accuracy_score   :{accuracy_score(Y_test,y_pred6)}")
print(f"recall_score     :{recall_score(Y_test,y_pred6)}")
print(f"f1_score         :{f1_score(Y_test,y_pred6)}")
print(f"roc_auc_score    :{roc_auc_score(Y_test,y_pred6)}")
print(f"confusion_matrix :\n {confusion_matrix(Y_test,y_pred6)}")
print(f"classification_report :\n {classification_report(Y_test,y_pred6)}")

precision_score  :0.8426165803108808
accuracy_score   :0.844632768361582
recall_score     :0.8377334191886671
f1_score         :0.8401679044236358
roc_auc_score    :0.8444637702189507
confusion_matrix :
 [[1390  243]
 [ 252 1301]]
classification_report :
               precision    recall  f1-score   support

           0       0.85      0.85      0.85      1633
           1       0.84      0.84      0.84      1553

    accuracy                           0.84      3186
   macro avg       0.84      0.84      0.84      3186
weighted avg       0.84      0.84      0.84      3186